docs/reference/dapi-endpoints-core-grpc-endpoints.md
docs/reference/dapi-endpoints-grpc-overview.md
docs/reference/dapi-endpoints-json-rpc-endpoints.md
docs/reference/dapi-endpoints-platform-endpoints.md
docs/tutorials/connecting-to-testnet.md
docs/tutorials/contracts-and-documents/register-a-data-contract.md
docs/tutorials/contracts-and-documents/retrieve-documents.md
docs/tutorials/identities-and-names/register-a-name-for-an-identity.md
docs/tutorials/identities-and-names/retrieve-a-name.md
docs/tutorials/identities-and-names/update-an-identity.md
docs/tutorials/node-setup/connect-to-a-network-dash-masternode.md

Preview build: https://dash-docs-platform--10.org.readthedocs.build/en/10/

docs: multi-language code blocks to tabs

---

_templates/sidebar-main.html
docs/dapi-client-js/usage/core/broadcasttransaction.md
docs/dapi-client-js/usage/core/generatetoaddress.md
docs/dapi-client-js/usage/core/getbestblockhash.md
docs/dapi-client-js/usage/core/getblockbyhash.md
docs/dapi-client-js/usage/core/getblockbyheight.md
docs/dapi-client-js/usage/core/getblockhash.md
docs/dapi-client-js/usage/core/getmnlistdiff.md
docs/dapi-client-js/usage/core/getstatus.md
docs/dapi-client-js/usage/core/gettransaction.md
docs/dapi-client-js/usage/core/subscribetotransactionswithproofs.md
docs/dapi-client-js/usage/platform/broadcaststatetransition.md
docs/dapi-client-js/usage/platform/getdatacontract.md
docs/dapi-client-js/usage/platform/getdocuments.md
docs/dapi-client-js/usage/platform/getidentity.md
docs/dapi-client-js/usage/platform/getidentitybyfirstpublickey.md
docs/dapi-client-js/usage/platform/getidentityidbyfirstpublickey.md
docs/sdk-js/platform/names/resolve.md

Preview build: https://dash-docs-platform--22.org.readthedocs.build/en/22/

docs: minor refactoring and typos

---

docs/reference/dapi-endpoints-core-grpc-endpoints.md
docs/reference/dapi-endpoints-json-rpc-endpoints.md
docs/reference/dapi-endpoints-platform-endpoints.md
docs/reference/dapi-endpoints.md

Preview build: https://dash-docs-platform--25.org.readthedocs.build/en/25/

fix: update previous version links

---

docs/tutorials/identities-and-names/update-an-identity.md

Correct syntax as reported by @kxcd
Preview build: https://dash-docs-platform--27.org.readthedocs.build/en/27/

fix: correct syntax error in tutorial

---

docs/tutorials/contracts-and-documents.md
docs/tutorials/contracts-and-documents/delete-documents.md
docs/tutorials/contracts-and-documents/register-a-data-contract.md
docs/tutorials/contracts-and-documents/retrieve-a-data-contract.md
docs/tutorials/contracts-and-documents/retrieve-documents.md
docs/tutorials/contracts-and-documents/submit-documents.md
docs/tutorials/contracts-and-documents/update-a-data-contract.md
docs/tutorials/contracts-and-documents/update-documents.md
docs/tutorials/identities-and-names.md
docs/tutorials/identities-and-names/register-a-name-for-an-identity.md
docs/tutorials/identities-and-names/register-an-identity.md
docs/tutorials/identities-and-names/retrieve-an-accounts-identities.md
docs/tutorials/identities-and-names/retrieve-an-identity.md
docs/tutorials/identities-and-names/topup-an-identity-balance.md
docs/tutorials/identities-and-names/update-an-identity.md

Allows auto-generated toc to be used
Preview build: https://dash-docs-platform--29.org.readthedocs.build/en/29/

refactor: update heading levels for contract and doc tutorials

---

docs/tutorials/contracts-and-documents.md
docs/tutorials/contracts-and-documents/register-a-data-contract.md
docs/tutorials/contracts-and-documents/retrieve-data-contract-history.md
docs/tutorials/contracts-and-documents/update-a-data-contract.md

Preview build: https://dash-docs-platform--28.org.readthedocs.build/en/28/

feat: add tutorials for new v0.25 functionality

---

docs/reference/data-contracts.md

Preview build: https://dash-docs-platform--38.org.readthedocs.build/en/38/

docs: v0.25.16 data contract update

---

docs/reference/dapi-endpoints-platform-endpoints.md
docs/reference/dapi-endpoints.md

Adds:
Only includes gRPCurl examples
Preview build: https://dash-docs-platform--40.org.readthedocs.build/en/40/

docs(reference): add missing endpoints

---

docs/reference/dapi-endpoints-platform-endpoints.md

Preview build: https://dash-docs-platform--41.org.readthedocs.build/en/41/

chore: update fields name format to be consistent

---

docs/tutorials/contracts-and-documents/delete-documents.md
docs/tutorials/contracts-and-documents/register-a-data-contract.md
docs/tutorials/contracts-and-documents/submit-documents.md
docs/tutorials/contracts-and-documents/update-a-data-contract.md
docs/tutorials/contracts-and-documents/update-documents.md
docs/tutorials/identities-and-names/register-a-name-for-an-identity.md
docs/tutorials/identities-and-names/register-an-identity.md
docs/tutorials/identities-and-names/retrieve-an-accounts-identities.md
docs/tutorials/identities-and-names/topup-an-identity-balance.md
docs/tutorials/identities-and-names/transfer-credits-to-an-identity.md
docs/tutorials/identities-and-names/update-an-identity.md
docs/tutorials/send-funds.md

Preview build: https://dash-docs-platform--44.org.readthedocs.build/en/44/

chore: update sync start height to 875000 to improve sync time

---

docs/reference/dapi-endpoints-core-grpc-endpoints.md
docs/reference/dapi-endpoints-grpc-overview.md
docs/reference/dapi-endpoints-json-rpc-endpoints.md
docs/reference/dapi-endpoints-platform-endpoints.md

Preview build: https://dash-docs--50.org.readthedocs.build/projects/platform/en/50/docs/reference/dapi-endpoints-platform-endpoints.html

docs: convert to custom named tabs

---

conf.py

Needed so "Edit on GitHub" point to the current docs

chore: change github_version to 1.0-dev

---

docs/reference/dapi-endpoints-core-grpc-endpoints.md
docs/reference/dapi-endpoints-platform-endpoints.md
docs/reference/dapi-endpoints.md

Deprecate / add recent endpoints. This update includes gRPC examples for all additions
Preview build: https://dash-docs--57.org.readthedocs.build/projects/platform/en/57/docs/reference/dapi-endpoints-platform-endpoints.html

docs: endpoint update

---

docs/tutorials/connecting-to-testnet.md

Fixes issue introduced in #59 
Preview build: https://dash-docs-platform--60.org.readthedocs.build/en/60/

chore: fix incorrect version

---

docs/explanations/nft.md
docs/index.md

Adds an explanation section for NFTs
Preview build: https://dash-docs--61.org.readthedocs.build/projects/platform/en/61/docs/explanations/nft.html

docs: add nft explanation section

---

docs/tutorials/node-setup/connect-to-a-network-dash-masternode.md

Preview build: https://dash-docs-platform--69.org.readthedocs.build/en/69/

docs: provide a link to installation section

---

.readthedocs.yml

Prevents newer builds from completing

build: disable pdf generation

---

docs/reference/dapi-endpoints-platform-endpoints.md
docs/reference/dapi-endpoints.md

Add info about masternode identities, update identity ids used in examples, and add `getStatus`
Preview build: https://dash-docs--80.org.readthedocs.build/projects/platform/en/80/docs/reference/dapi-endpoints-platform-endpoints.html#getidentity

docs: dapi endpoint update

---

_templates/sidebar-main.html
docs/index.md
docs/reference/frequently-asked-questions.md
docs/resources/faq.md

Add some frequent questions related to DPNS names
Preview build: https://dash-docs--87.org.readthedocs.build/projects/platform/en/87/docs/resources/faq.html#dpns-names

docs: add dpns faq items, rename and move faq

---

docs/index.md
docs/resources/faq.md

Preview build: https://dash-docs-platform--88.org.readthedocs.build/en/88/

docs: update dpns faqs

---

docs/resources/faq.md

Update FAQ with questions from [Discord](https://discord.com/channels/484546513507188745/1311579340034539611/1311583266976829450)
Preview build: https://dash-docs--92.org.readthedocs.build/projects/platform/en/92/docs/resources/faq.html

docs: faq additions

---

_static/css/pydata-overrides.css
_static/js/pydata-search-close.js
_templates/sidebar-main.html
conf.py
requirements.txt

Updates the Pydata theme and Sphinx along with other dependencies. Performs related updates (config, CSS, etc.) to make everything work with the updated deps. Related to dashpay/docs#459
Preview: https://dash-docs--94.org.readthedocs.build/projects/platform/en/94/

chore: update dependencies to latest release

---

docs/explanations/platform-protocol-state-transition.md
docs/protocol-ref/document.md
docs/protocol-ref/errors.md
docs/protocol-ref/identity.md
docs/protocol-ref/overview.md
docs/protocol-ref/state-transition.md

Preview build: 
- [DPP - Identity](https://dash-docs--102.org.readthedocs.build/projects/platform/en/102/docs/protocol-ref/identity.html)
- [DPP - error codes](https://dash-docs--102.org.readthedocs.build/projects/platform/en/102/docs/protocol-ref/errors.html)

docs(ref): update identity and error code info

---

docs/reference/glossary.md

Based on feedback from Discord

chore: add epoch and era to glossary

---

docs/intro/what-is-dash-platform.md

Add video to the what is platform page
Preview build: https://dash-docs--107.org.readthedocs.build/projects/platform/en/107/docs/intro/what-is-dash-platform.html

docs: add evo video

---

docs/dapi-client-js/overview.md
docs/intro/what-is-dash-platform.md
docs/reference/glossary.md

Preview build: https://dash-docs-platform--118.org.readthedocs.build/en/118/

chore: merge v1 into develop

---

_templates/sidebar-main.html
scripts/sync_sidebar.py

The sidebar on the main index page was manually created to includes links to Core and User docs. This PR adds a script to automatically update that sidebar while including the manual sections so it no longer has to be manually updated when new pages are added.

feat: generate sidebar from index

---

docs/reference/dapi-endpoints-platform-endpoints.md

Add testnet response data for new endpoints now that v2 is on testnet
Preview build: https://dash-docs-platform--125.org.readthedocs.build/en/125/

docs(api): update endpoint responses with testnet data

---

docs/resources/faq.md
requirements.txt

Preview build: https://dash-docs-platform--127.org.readthedocs.build/en/127/

chore: merge 1.0 into develop

---

conf.py

Correct year and platform version

config: minor conf.py updates
