dashpay/docs-platform

- docs/explanations/platform-consensus.md
- docs/explanations/platform-protocol.md
- docs/protocol-ref/errors.md
- docs/protocol-ref/state-transition.md
- docs/reference/dapi-endpoints-platform-endpoints.md
- docs/reference/dapi-endpoints.md
- docs/tutorials/connecting-to-testnet.md
- docs/tutorials/contracts-and-documents/register-a-data-contract.md
- docs/tutorials/identities-and-names/register-a-name-for-an-identity.md
- docs/tutorials/identities-and-names/topup-an-identity-balance.md
- docs/tutorials/identities-and-names/update-an-identity.md
- docs/tutorials/node-setup/connect-to-a-network-dash-core-full-node.md
Imported a backup from readme.io created on 2023-08-17
> chore: update based on current import

- docs/dapi-client-js/overview.md
- docs/dapi-client-js/quick-start.md
- docs/dapi-client-js/usage/core/broadcasttransaction.md
- docs/dapi-client-js/usage/core/core.md
- docs/dapi-client-js/usage/core/generatetoaddress.md
- docs/dapi-client-js/usage/core/getbestblockhash.md
- docs/dapi-client-js/usage/core/getblockbyhash.md
- docs/dapi-client-js/usage/core/getblockbyheight.md
- docs/dapi-client-js/usage/core/getblockhash.md
- docs/dapi-client-js/usage/core/getmnlistdiff.md
- docs/dapi-client-js/usage/core/getstatus.md
- docs/dapi-client-js/usage/core/gettransaction.md
- docs/dapi-client-js/usage/core/subscribetotransactionswithproofs.md
- docs/dapi-client-js/usage/dapi-client.md
- docs/dapi-client-js/usage/dapiclient.md
- docs/dapi-client-js/usage/platform/broadcaststatetransition.md
- docs/dapi-client-js/usage/platform/getdatacontract.md
- docs/dapi-client-js/usage/platform/getdocuments.md
- docs/dapi-client-js/usage/platform/getidentity.md
- docs/dapi-client-js/usage/platform/getidentitybyfirstpublickey.md
- docs/dapi-client-js/usage/platform/getidentityidbyfirstpublickey.md
- docs/dapi-client-js/usage/platform/platform.md
- docs/dapi-client-js/usage/usage.md
- docs/index.md
- scripts/1-readme-rename.sh
Preview build: https://dash-docs-platform--11.org.readthedocs.build/en/11/
> docs: import docsify (dapi-client)

- docs/dapi-client-js/overview.md
- docs/explanations/dapi.md
- docs/index.md
- docs/intro/what-is-dash.md
- docs/protocol-ref/overview.md
- docs/reference/dapi-endpoints.md
- docs/resources/repository-overview.md
- docs/sdk-js/overview.md
- docs/tutorials/introduction.md
Preview build: https://dash-docs-platform--13.org.readthedocs.build/en/13/
> docs: update landing page

- docs/other/incentives.md
- docs/reference/dapi-endpoints-platform-endpoints.md
- docs/tutorials/connecting-to-testnet.md
- docs/tutorials/contracts-and-documents/delete-documents.md
- docs/tutorials/contracts-and-documents/register-a-data-contract.md
- docs/tutorials/contracts-and-documents/retrieve-a-data-contract.md
- docs/tutorials/contracts-and-documents/retrieve-documents.md
- docs/tutorials/contracts-and-documents/submit-documents.md
- docs/tutorials/contracts-and-documents/update-a-data-contract.md
- docs/tutorials/contracts-and-documents/update-documents.md
- docs/tutorials/identities-and-names/retrieve-a-name.md
- docs/tutorials/identities-and-names/update-an-identity.md
- docs/tutorials/introduction.md
- scripts/2-readme-link-conversion-from-backup.sh
Incorporates the initial v0.25 changes made to readme.io
Preview build: https://dash-docs-platform--23.org.readthedocs.build/en/23/
> docs: v0.25 readme sync

- docs/reference/dapi-endpoints-platform-endpoints.md
Updates example dapi-client and dapi-grpc code. Now more reliant on DPP to handle deserializing platform objects.
Preview build: https://dash-docs-platform--26.org.readthedocs.build/en/26/
> docs: v0.25 dapi endpoint example updates

- docs/reference/dapi-endpoints-platform-endpoints.md
- docs/reference/dapi-endpoints.md
Adds the new `getDataContractHistory` endpoint from Dash Platform v0.25
Preview build: https://dash-docs-platform--31.org.readthedocs.build/en/31/
> docs(reference): add getDataContractHistory info

- docs/tutorials/connecting-to-testnet.md
- docs/tutorials/introduction.md
- docs/tutorials/node-setup/connect-to-a-network-dash-masternode.md
Bump minimum Node.JS version as we drop support of outdated Node.js versions
Preview build: https://dash-docs-platform--34.org.readthedocs.build/en/34/
> chore: bump Node.JS requirements to v20 (current LTS)

- docs/explanations/platform-protocol-data-contract.md
- docs/protocol-ref/data-contract.md
- docs/tutorials/contracts-and-documents/register-a-data-contract.md
- docs/tutorials/contracts-and-documents/update-a-data-contract.md
Changes due to https://github.com/dashpay/platform/pull/1594 which requires all document properties to use a new `position` field to support backwards compatibility when contracts are updated. Related to https://github.com/thephez/readme-tutorial-testing/pull/51.
Preview build: https://dash-docs-platform--35.org.readthedocs.build/en/35/
> docs: update contract register and update

- docs/tutorials/contracts-and-documents/register-a-data-contract.md
$ref hasn't been supported since v0.22 and won't be until after v1 so it makes sense to remove for now to prevent confusion.
Preview build: https://dash-docs-platform--36.org.readthedocs.build/en/36/
> chore: remove ref examples

- docs/reference/dapi-endpoints-platform-endpoints.md
- docs/reference/dapi-endpoints.md
Platform v0.25.16 introduced changes to version gRPC endpoints (https://github.com/dashpay/platform/pull/1522) which affected some request and response details.
Preview build: https://dash-docs-platform--39.org.readthedocs.build/en/39/
> chore: v0.25 gRPC updates

- docs/tutorials/identities-and-names.md
- docs/tutorials/identities-and-names/transfer-credits-to-an-identity.md
Recent versions of Dash Platform have enabled the ability to transfer credits between identities. This pull request adds a tutorial to demonstrate this feature.
Preview build: https://dash-docs--43.org.readthedocs.build/projects/platform/en/43/docs/tutorials/identities-and-names/transfer-credits-to-an-identity.html
> feat: add credit transfer tutorial

- docs/tutorials/connecting-to-testnet.md
- docs/tutorials/contracts-and-documents/register-a-data-contract.md
- docs/tutorials/contracts-and-documents/retrieve-documents.md
- docs/tutorials/contracts-and-documents/update-a-data-contract.md
- docs/tutorials/identities-and-names/register-a-name-for-an-identity.md
- docs/tutorials/identities-and-names/retrieve-a-name.md
- docs/tutorials/identities-and-names/update-an-identity.md
- docs/tutorials/node-setup/connect-to-a-network-dash-masternode.md
Previously tab names were automatically created based on the type of code they contained. Switched to use [standard tabs](https://sphinx-design.readthedocs.io/en/latest/tabs.html) instead of code-specific ones so we can give the tabs custom names. This PR updates the tutorial section with the change.
Preview build: https://dash-docs-platform--49.org.readthedocs.build/en/49/
> docs: convert tutorials to named tabs

- docs/tutorials/identities-and-names/topup-an-identity-balance.md
Right now the example code for [Topup an identity’s balance](https://docs.dash.org/projects/platform/en/stable/docs/tutorials/identities-and-names/topup-an-identity-balance.html#code) results in an error:
```
Something went wrong:
[StateTransitionBroadcastError: Asset lock transaction 7d3496d9835cd8885e56fb7fda0021ea60bf7ca3e902b5fd604d1298fceabce2 output 0 only has 1000 credits left out of 1000 initial credits on the asset lock but needs 50000 credits to start processing] {
code: 10530,
cause: IdentityAssetLockTransactionOutPointNotEnoughBalanceError {
__wbg_ptr: 3280960
}
}
```
Raising the value of `topUpAmount` above `50000` as mentioned in the error fixes the issue.
[Here's a quick repro of the error if you want to validate the fix](https://github.com/ajcwebdev/dash-error-repro). …
> fix: raise topUpAmount value

- docs/tutorials/connecting-to-testnet.md
Testnet is not currently on the latest dev release, so this pins the sdk version to one that matches testnet.
Preview build: https://dash-docs-platform--59.org.readthedocs.build/en/59/
> docs: pin sdk version to testnet version

- docs/explanations/nft.md
- docs/tutorials/contracts-and-documents/register-a-data-contract.md
Although the JS SDK does not support the state transitions required to transfer documents, set prices, or purchase documents, contracts for NFTs can still be registered since they're regular contracts with some options configured.
This PR includes an example contract for a simple NFT in the contract registration tutorial (to show how the relevant contract options might be set). Technically NFT documents for the contract can be created/deleted with the JS SDK also. Since doc create/delete work identically to any other doc, those tutorials were not updated.
Preview: https://dash-docs--62.org.readthedocs.build/projects/platform/en/62/docs/tutorials/contracts-and-documents/register-a-data-contract.html
> docs: update contract registration tutorial to include nft example

- _templates/sidebar-main.html
- docs/index.md
- docs/sdk-rs/overview.md
- docs/sdk-rs/quick-start.md
Shows how to set up a client using Dash Core as a context provider to support proofs. Includes an example of retrieving an identity with proofs. Uses info from https://www.dash.org/blog/strategy-tests-usage-guide/ and rs-sdk README/tests/examples.
Preview build: [Overview](https://dash-docs--63.org.readthedocs.build/projects/platform/en/63/docs/sdk-rs/overview.html) and [Quick Start](https://dash-docs--63.org.readthedocs.build/projects/platform/en/63/docs/sdk-rs/quick-start.html)
> docs: add some minimal rust sdk info

- docs/explanations/identity.md
Adds some info about masternode identities
Preview build: https://dash-docs--64.org.readthedocs.build/projects/platform/en/64/docs/explanations/identity.html#masternode-identities
> docs: update identity info

- docs/explanations/dpns.md
Describe the high-level resolution process used for contested names. Based on the [DPNS contract](https://github.com/dashpay/platform/blob/v1.0.0-beta.3/packages/dpns-contract/schema/v1/dpns-contract-documents.json) and info from dashpay/platform#1878
Preview build: https://dash-docs--65.org.readthedocs.build/projects/platform/en/65/docs/explanations/dpns.html#conflict-resolution
> docs: update dpns registration info

- docs/sdk-js/platform/names/register.md
- docs/sdk-js/platform/names/resolvebyrecord.md
- docs/tutorials/identities-and-names/register-a-name-for-an-identity.md
- docs/tutorials/identities-and-names/retrieve-a-name.md
Platform v1 changed the name/identity relationship and removed the unique/alias record types. Now it only uses a single identity record type since https://github.com/dashpay/platform/pull/1984
Preview build: https://dash-docs-platform--72.org.readthedocs.build/en/72/
> docs: names no longer use dashUnique and dashAlias IdentityIds

- docs/tutorials/connecting-to-testnet.md
Now that [v1.1 is released](https://github.com/dashpay/platform/releases/tag/v1.1.0), we can go back to installing the latest stable version.
Preview build: https://dash-docs-platform--76.org.readthedocs.build/en/76/
> docs: update to install the latest stable sdk release

- docs/explanations/nft.md
- docs/explanations/platform-protocol-document.md
- docs/protocol-ref/data-contract.md
- docs/reference/data-contracts.md
- docs/sdk-rs/overview.md
Significant update of data contract page to align with Platform v1. Expanded details to include newest configuration options.
Preview build: https://dash-docs--75.org.readthedocs.build/projects/platform/en/75/docs/reference/data-contracts.html
> docs: data contract updates

- docs/sdk-js/overview.md
- docs/tutorials/connecting-to-testnet.md
- docs/tutorials/introduction.md
- docs/tutorials/setup-sdk-client.md
Since it doesn't request proofs it's less secure than it could be otherwise
Preview build: https://dash-docs-platform--79.org.readthedocs.build/en/79/
> docs: add warnings about the js sdk

- conf.py
- docs/ai-prompt.md
- docs/reference/dapi-endpoints-platform-endpoints.md
- docs/reference/dapi-endpoints.md
Preview build: https://dash-docs--81.org.readthedocs.build/projects/platform/en/81/docs/reference/dapi-endpoints.html#platform-grpc-service
> docs(ref): endpoint update for v1.3

- _templates/sidebar-main.html
- docs/tutorials/connecting-to-testnet.md
- docs/tutorials/contracts-and-documents/retrieve-a-data-contract.md
- docs/tutorials/identities-and-names.md
- docs/tutorials/identities-and-names/withdraw-an-identity-balance.md
- docs/tutorials/identities-and-names/withdraw-credits-from-an-identity.md
- docs/tutorials/setup-sdk-client.md
Platform v1.4 SDK will connect to mainnet by default instead of testnet so the network option has been set to continue using testnet. This PR also adds a tutorial for withdrawing credits back to Dash.
Preview build: https://dash-docs--82.org.readthedocs.build/projects/platform/en/82/docs/tutorials/identities-and-names/withdraw-an-identity-balance.html
> docs: update tutorials for v1.4

- conf.py
- requirements.txt
Readthedocs removed their analytics integration (see https://github.com/readthedocs/readthedocs.org/issues/9530#issuecomment-2233541583). This PR introduces use of an addon to re-enable that capability.
> feat: add alternate analytics config

- docs/explanations/identity.md
- docs/index.md
- docs/intro/testnet.md
- docs/tutorials/create-and-fund-a-wallet.md
Testnet insight is now located at https://insight.testnet.networks.dash.org/insight/.
Preview build: https://dash-docs-platform--95.org.readthedocs.build/en/95/
> docs: update insight testnet urls

- docs/protocol-ref/data-contract.md
Updates data size info based on feedback from @pshenmic. Also does some other misc cleanup (links, formatting, etc.). More updates are required in a future PR.
Preview build: https://dash-docs-platform--100.org.readthedocs.build/en/100/
> docs: update data contract page 1

- docs/intro/what-is-dash-platform.md
- docs/reference/glossary.md
Preview build: https://dash-docs-platform--108.org.readthedocs.build/en/108/
> chore: merge 1.0 into develop

- _templates/sidebar-main.html
- conf.py
- docs/dapi-client-js/usage/core/broadcasttransaction.md
- docs/intro/what-is-dash.md
- docs/protocol-ref/identity.md
- docs/protocol-ref/state-transition.md
- docs/reference/dapi-endpoints-core-grpc-endpoints.md
- docs/reference/dapi-endpoints-platform-endpoints.md
- docs/reference/dapi-endpoints.md
- docs/reference/glossary.md
- docs/sdk-js/getting-started/core-concepts.md
Use the new link in the integrated repo instead of the sub-project link that may eventually be deprecated
Preview build: https://dash-docs-platform--109.org.readthedocs.build/en/109/
> chore: update links to core

- docs/explanations/platform-protocol-state-transition.md
- docs/protocol-ref/document.md
- docs/protocol-ref/state-transition.md
[Documents](https://dash-docs--110.org.readthedocs.build/projects/platform/en/110/docs/protocol-ref/document.html)
Updates details and adds the NFT-related state transitions (transfer, purchase, update price)
Preview build: https://dash-docs-platform--110.org.readthedocs.build/en/110/
> docs(ref): document updates

- docs/dapi-client-js/overview.md
For some reason the label in the eval-rst doesn't work when followed immediately by the admonition. Relocating the heading fixes it.
Preview build: https://dash-docs-platform--111.org.readthedocs.build/en/111/
> fix: relocate heading to fix linking issue

- docs/index.md
- docs/protocol-ref/data-contract-document.md
- docs/protocol-ref/data-contract-token.md
- docs/protocol-ref/data-contract.md
- docs/protocol-ref/state-transition.md
- docs/protocol-ref/token.md
[Token transitions](https://dash-docs--112.org.readthedocs.build/projects/platform/en/112/docs/protocol-ref/token.html)
Preview build: https://dash-docs--112.org.readthedocs.build/projects/platform/en/112/docs/protocol-ref/token.html
> docs(ref): add token transition details

- docs/index.md
- docs/tutorials/building-platform.md
Platform build instructions. Tested on Ubuntu 22 and 24 LTS
Preview build: https://dash-docs--98.org.readthedocs.build/projects/platform/en/98/docs/tutorials/building-platform.html
> docs: add instructions for setting up linux to build platform

- conf.py
- docs/explanations/tokens.md
Provides additional detail on token distribution options. Info based on https://github.com/dashpay/platform/blob/58492447c3733c80aca6251baade82558fbddbae/packages/rs-dpp/src/data_contract/associated_token/token_perpetual_distribution/distribution_function/mod.rs
Preview build: https://dash-docs--114.org.readthedocs.build/projects/platform/en/114/docs/explanations/tokens.html#perpetual-distribution-options
> docs: add token distribution rule info

- docs/reference/dapi-endpoints-core-grpc-endpoints.md
Preview build: https://dash-docs--115.org.readthedocs.build/projects/platform/en/115/docs/reference/dapi-endpoints-core-grpc-endpoints.html#subscribetotransactionswithproofs
> docs(api): add js example for subscribeToTransactionsWithProofs

- _templates/sidebar-main.html
- docs/index.md
- docs/reference/dapi-endpoints-core-grpc-endpoints.md
- docs/reference/dapi-endpoints-json-rpc-endpoints.md
- docs/reference/dapi-endpoints-platform-endpoints.md
Switch links to point to v1 of the docs
Preview build: https://dash-docs-platform--116.org.readthedocs.build/en/116/
> docs: update previous version links

- docs/explanations/tokens.md
- docs/protocol-ref/data-contract.md
- docs/protocol-ref/errors.md
- docs/protocol-ref/token.md
- docs/reference/dapi-endpoints-platform-endpoints.md
- docs/tutorials/building-platform.md
Preview build: https://dash-docs-platform--121.org.readthedocs.build/en/121/
> docs: more v2

- docs/explanations/tokens.md
- docs/protocol-ref/data-contract-document.md
- docs/protocol-ref/data-contract-token.md
- docs/protocol-ref/data-contract.md
- docs/protocol-ref/document.md
- docs/protocol-ref/errors.md
- docs/protocol-ref/identity.md
- docs/protocol-ref/state-transition.md
- docs/protocol-ref/token.md
V2 docs originally linked to the v2.0-dev branch that was active during development. This PR updates those links to the latest (v2.0.1) release.
Preview build: https://dash-docs-platform--128.org.readthedocs.build/en/128/
> chore: update dpp links to 2.0.1 instead of v2-dev

- docs/resources/faq.md
- requirements.txt
Preview build: https://dash-docs-platform--129.org.readthedocs.build/en/129/
> chore: merge main into 2.0.0
